feat: add class based tooling for filters
eduNEXT/openedx-filters pull request #16
Opened 2021-09-16 20:22 UTC by mariajgrimaldi

**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2021-11-05 17:45 UTC, felipemontoya commented on openedx_filters/tooling.py
> +                        "Pipeline stopped by '%s' for returning an object.",
```suggestion
                        "Pipeline stopped by '%s' for returning an object.",
```
```suggestion
                        "Pipeline stopped by '%s' for returning an object instead of a dict.",
```

2021-11-05 19:29 UTC, felipemontoya requested changes
Also, the discussion we had about extra metadata passed to the filter function

2021-11-15 14:33 UTC, mariajgrimaldi commented on openedx_filters/tooling.py
> +                        "Pipeline stopped by '%s' for returning an object.",
Some time ago, we talked about having partial pipelines, so returning an object doesn't mean the filter is broken. So, for example, if X, then I want to stop the execution. If Y, I want to continue. To stop the execution, I'd use a partial pipeline

2021-11-15 17:18 UTC, mariajgrimaldi commented on openedx_filters/tooling.py
> +                if raise_exception:
Already considered :+1: thank you!

2021-11-15 17:19 UTC, mariajgrimaldi commented on openedx_filters/tooling.py
> +                    exceptions (OpenEdxFilterException) are caught and the execution
Thanks for the explanation! I updated the docstring

2021-11-16 19:27 UTC, felipemontoya requested changes

2021-11-16 19:27 UTC, felipemontoya commented on openedx_filters/filters.py
> +    def do_filter(self, **kwargs):
`run` ?

2021-11-16 19:27 UTC, felipemontoya commented on openedx_filters/tooling.py
> +                if fail_silently:
Should we at least log it here before being so silent?

2021-11-23 03:31 UTC, felipemontoya commented on openedx_filters/tooling.py
> +                if not isinstance(result, dict):
This is very strict.
If the Step returns something different than a dict, then it stops.

Does that mean that if I want to return nothing, but allow other Steps to continue I should return `{}` ?

2021-11-23 03:43 UTC, felipemontoya commented on openedx_filters/tooling.py
> +                result = step_runner.run(**accumulated_output)
during this run we are ignoring the configured 'log_level' for the pipeline. This is what will come in PR#17, right?

2021-11-23 14:28 UTC, mariajgrimaldi commented on openedx_filters/tooling.py
> +                result = step_runner.run(**accumulated_output)
Right!

2021-11-23 14:28 UTC, mariajgrimaldi commented on openedx_filters/tooling.py
> +                if not isinstance(result, dict):
Yes, or the arguments that the filter received. We inherited this behavior from the social core pipeline.

2021-11-23 14:59 UTC, felipemontoya approved these changes

2021-11-24 12:53 UTC, merged