feat: add 1st batch of filters
eduNEXT/openedx-filters pull request #20
Opened 2021-11-25 23:11 UTC by mariajgrimaldi

**Description:** 
This PR adds:

* PreRegisterFilter
* PreLoginFilter

Used by edx-platform.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

2021-11-27 16:46 UTC, mariajgrimaldi commented on openedx_filters/learning/auth.py
> +"""
should we move all filters to `filters.py` file? @felipemontoya to be compliant with openedx-events

2021-12-14 04:11 UTC, felipemontoya requested changes

2021-12-14 04:11 UTC, felipemontoya commented on openedx_filters/learning/auth.py
> +        "password",
Is `password` enough? should we be censoring all the fields at https://github.com/edx/edx-platform/blob/master/common/djangoapps/track/middleware.py#L64

2021-12-14 04:11 UTC, felipemontoya commented on openedx_filters/learning/auth.py
> +        sensitive_data = cls.remove_sensitive_form_data(form_data)
This should not be a blocking issue, but is this something that should be handled at the core before we even send the call to the filter?
Could it be that we end up forgetting that sensitive data is passed to the filter class and eventually end up logging it?

2021-12-14 04:11 UTC, felipemontoya commented on openedx_filters/learning/auth.py
> +class PreLoginFilter(OpenEdxPublicFilter):
Much the same as the naming of the filter above, is PreLogin the name or should we go with StudentLoginFilter?

2021-12-14 04:12 UTC, felipemontoya commented on openedx_filters/learning/auth.py
> +class PreRegisterFilter(OpenEdxPublicFilter):
This probably also affects the naming of the PreEnrollmentFilter and the implementing PR as well

2021-12-14 13:40 UTC, mariajgrimaldi commented on openedx_filters/learning/auth.py
> +class PreRegisterFilter(OpenEdxPublicFilter):
Great suggestion. I'll go with the `StudentRegistrationRequested` because it's the closest to the events naming convention.

2021-12-14 14:12 UTC, mariajgrimaldi commented on openedx_filters/learning/auth.py
> +        sensitive_data = cls.remove_sensitive_form_data(form_data)
Handling sensitive data within the filter implementation was Dave's recommendation in [PR 29449](https://github.com/edx/edx-platform/pull/29449#discussion_r761602507). And as I see it, the filter implementation should decide what to pass on the pipeline -in its context of login, registration, etc.- instead of relying on the core, this way we encapsulate implementation details inside the filter. What do you think?

2021-12-14 16:22 UTC, felipemontoya commented on openedx_filters/learning/auth.py
> +        sensitive_data = cls.remove_sensitive_form_data(form_data)
This is good then. I had not seen Dave's comment on the other PR yet.

2021-12-14 16:31 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +    class PreventRegister(OpenEdxFilterException):
Nit: "preventRegistration" ?

2021-12-14 16:32 UTC, felipemontoya approved these changes
This is looking almost ready to me now. I left a comment about the name of the exception but once that is in, I''m good with merging.

2021-12-15 21:37 UTC, merged