[WIP] Mjg/2nd filters batch
eduNEXT/openedx-filters pull request #22
Opened 2021-12-13 17:52 UTC by mariajgrimaldi

**Description:** Describe in a couple of sentences what this PR adds

**JIRA:** Link to JIRA ticket

**Dependencies:** dependencies on other outstanding PRs, issues, etc. 

**Merge deadline:** List merge deadline (if any)

**Installation instructions:** List any non-trivial installation 
instructions.

**Testing instructions:**

1. Open page A
2. Do thing B
3. Expect C to happen
4. If D happened instead - check failed.

**Reviewers:**
- [ ] tag reviewer 
- [ ] tag reviewer 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** List any concerns about this PR - inelegant 
solutions, hacks, quick-and-dirty implementations, concerns about 
migrations, etc.

2022-02-11 01:35 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        data = super().run_pipeline(context=context)
https://github.com/openedx/edx-platform/pull/29840/files#diff-01248664af6299131788a15aa23bc8641019bc3b630bf5ef48104cdb31698de4R647

for context

2022-02-11 01:35 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        data = super().run_pipeline(context=context)
would we be open here to add a template as well?

what if we also add a way to return a rendered page? would that be too much?

2022-02-11 01:35 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        data = super().run_pipeline(context=context)
perhaps we can add a template_name and that is enough, a plugin developer can alter the context and change the template name. Both of those then go to the render_to_response function and we get all the flexibility without passing heavy template objects around.

2022-02-11 01:35 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        data = super().run_pipeline(context=context)
https://github.com/openedx/edx-platform/pull/29840/files#diff-cfab8ddd186c3bde2aec4290ddf2926c4c00c1ee294571f67b969f2980ce6d97R1034

2022-02-11 01:35 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        data = super().run_pipeline(context=context)
same as the previous comment about passing the template_name

2022-02-14 15:17 UTC, mariajgrimaldi commented on openedx_filters/learning/filters.py
> +        data = super().run_pipeline(context=context)
> would we be open here to add a template as well?
That's powerful! Thank you :smiley: 

> what if we also add a way to return a rendered page? would that be too much?
Do you mean e.g `render_to_response('courseware/course_about.html', context)`? the thing is, can we modify this object?

2022-02-15 16:56 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        data = super().run_pipeline(context=context)
I see you took the route of the template_name. That is good for me

2022-02-15 16:56 UTC, felipemontoya approved these changes

2022-02-15 16:57 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        data = super().run_pipeline(context=context)
We might have to touch on this and explain that reasoning in the pr that uses these filters at the platform

2022-02-16 01:51 UTC, felipemontoya requested changes
just found this while trying the edx-platform PR

2022-02-16 01:51 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        return data.get("context", "custom_template")
data.get("context"), data.get("custom_template")

2022-02-16 01:52 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        return data.get("context", "custom_template")
The docstring is missing the custom_template entry as well

2022-02-16 01:52 UTC, felipemontoya commented on openedx_filters/learning/filters.py
> +        return data.get("context")
we need to return the template_name

2022-02-22 23:31 UTC, felipemontoya approved these changes

2022-02-23 13:18 UTC, merged